"""The versioned migration runner: the H0 foundation tests.

Covers the six code gates the implementation plan names for migrations:

- fresh DB: an empty directory boots and the ledger records every revision;
- repeat: consecutive boots apply nothing new and change nothing;
- checksum mismatch: editing a committed migration fails startup;
- unknown/missing revision: a ledger this build does not know fails startup;
- interrupted migration: a failure inside the batch rolls everything back --
  no new revision, no partial DDL -- at every injected failure point;
- fixture upgrade: a checked-in legacy-schema fixture (generated by
  ``fixtures/generate_legacy_fixture.py`` from the last published schema
  contract) upgrades with every legacy table, row and index intact.
"""

from __future__ import annotations

import sqlite3
import threading
from pathlib import Path

import pytest
from pharos.db import migrations
from pharos.db.migrations import Migration, MigrationError, run_migrations, verify_migrations

FIXTURES = Path(__file__).parent / "fixtures"

_HISTORICAL_CHECKSUMS = {
    "0001_schema_ledger": "d178d412bd45a898811a1514ebd707dfcee37a568a85970e516d397e10524568",
    "0002_harness_definitions_config": (
        "808b1d4e3709266fabce4e6ed53275322ba3c5b982888b177e2ded17541f2695"
    ),
    "0003_harness_runs": "63eed51b4d8a143705b7622ec03b6fbc7676d870d7b211f063f7a97734b5cf48",
    "0004_harness_steps_attempts": (
        "404753a6bd2162e89cabbe3700e1c646566a6c1e08d67674c2222b4ba18ff609"
    ),
    "0005_harness_events": "66ceca6cef0d602c75af122dc48c6a62aa080e3d7e5cbc1e567937b8c773ebb2",
    "0006_harness_artifacts_links_releases": (
        "0afafb6feeaa3ee90d67a0981934345c7fffdd38f8ec695d10e65831be0c98b8"
    ),
    "0007_harness_approvals_schedules_usage": (
        "ae6c68b9af71efb7f89d6d53250f6921ded1b5e6480302dd922915ade1499dc0"
    ),
    "0008_harness_attempt_runtime_provenance": (
        "1ac5cc6b7cc61ec69997d11a56aab2a04a1f73dc1d9d745d795111adaa62b945"
    ),
    "0009_harness_attempt_runtime_identity": (
        "68781cafaab6c981ab08976dbbac90c2ecb3260fd07d20317b14935d59d74fb4"
    ),
}


def _insert_attempt(
    conn: sqlite3.Connection,
    attempt_id: str,
    *,
    state: str,
    runtime_session_id: str | None = None,
    child_pid: int | None = None,
) -> None:
    """Insert the minimum valid run/step/Attempt graph for constraint tests."""
    # Fresh migration-only databases do not include the legacy users table;
    # production bootstrap creates it before harness rows are written.
    conn.execute("CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY)")
    config_id = f"config-{attempt_id}"
    run_id = f"run-{attempt_id}"
    step_id = f"step-{attempt_id}"
    conn.execute(
        "INSERT INTO harness_config_revisions "
        "(id, snapshot_json, snapshot_sha256, gates_json, created_at) "
        "VALUES (?, '{}', ?, '{}', 1)",
        (config_id, config_id),
    )
    conn.execute(
        "INSERT INTO harness_runs "
        "(id, scope_type, scope_id, workflow_key, workflow_version, definition_sha256, "
        "config_revision_id, state, input_json, input_sha256, initiator, idempotency_key, "
        "created_at, updated_at) "
        "VALUES (?, 'user', 'constraint-test', 'workflow', 1, ?, ?, 'running', '{}', ?, "
        "'user', ?, 1, 1)",
        (run_id, run_id, config_id, run_id, run_id),
    )
    conn.execute(
        "INSERT INTO harness_steps "
        "(id, run_id, scope_type, scope_id, definition_step_key, instance_key, step_kind, "
        "definition_json, state, created_at, updated_at) "
        "VALUES (?, ?, 'user', 'constraint-test', 'step', ?, 'agent', '{}', 'running', 1, 1)",
        (step_id, run_id, attempt_id),
    )
    conn.execute(
        "INSERT INTO harness_attempts "
        "(id, step_id, run_id, scope_type, scope_id, attempt_no, state, "
        "runtime_session_id, child_pid) VALUES (?, ?, ?, 'user', 'constraint-test', 1, ?, ?, ?)",
        (attempt_id, step_id, run_id, state, runtime_session_id, child_pid),
    )


def _claim_attempt(
    conn: sqlite3.Connection,
    attempt_id: str,
    *,
    runtime_session_id: str,
    child_pid: int,
) -> None:
    conn.execute(
        "UPDATE harness_attempts SET runtime_session_id = ?, child_pid = ? WHERE id = ?",
        (runtime_session_id, child_pid, attempt_id),
    )


def _poisoned_migrations() -> tuple[Migration, ...]:
    """The real migrations plus a deliberately failing revision.

    The poison creates a table and then raises inside the same transaction,
    which is the exact shape of "DDL succeeded, ledger insert never ran" that
    the rollback gate must catch.
    """
    return migrations.MIGRATIONS + (
        Migration(
            revision="9999_poison",
            description="Deliberate failure for fault injection",
            statements=(
                "CREATE TABLE pharos_fault_probe (id INTEGER PRIMARY KEY)",
                # RAISE() only exists inside triggers; a missing column is the
                # equivalent deterministic statement error here.
                "SELECT nonexistent_column FROM pharos_fault_probe",
            ),
        ),
    )


def test_fresh_database_applies_every_revision(tmp_path: Path) -> None:
    db = tmp_path / "fresh.sqlite"
    applied = run_migrations(db)
    assert applied == [m.revision for m in migrations.MIGRATIONS]
    with sqlite3.connect(db) as conn:
        row = conn.execute(
            "SELECT revision, description FROM pharos_schema_migrations ORDER BY revision"
        ).fetchone()
    assert row is not None and row[0] == migrations.MIGRATIONS[0].revision


def test_historical_migration_checksums_are_immutable() -> None:
    assert {
        migration.revision: migration.checksum for migration in migrations.MIGRATIONS[:9]
    } == _HISTORICAL_CHECKSUMS


def test_0010_is_independently_valid_before_snapshot_upgrade(
    tmp_path: Path, monkeypatch
) -> None:
    db = tmp_path / "definition-binding-0010.sqlite"
    all_migrations = migrations.MIGRATIONS
    monkeypatch.setattr(migrations, "MIGRATIONS", all_migrations[:10])
    assert run_migrations(db)[-1] == "0010_harness_definition_bindings"
    with sqlite3.connect(db) as conn:
        conn.execute("PRAGMA foreign_keys=ON")
        conn.execute(
            "INSERT INTO harness_workflow_versions "
            "(id, workflow_key, version, definition_json, definition_sha256, "
            "input_schema, output_schema, created_at) "
            "VALUES ('workflow-0010', 'workflow', 1, '{}', ?, '{}', '{}', 'now')",
            ("a" * 64,),
        )
        conn.execute(
            "INSERT INTO harness_workflow_definition_bindings "
            "(binding_sha256, schema_version, workflow_key, workflow_version, "
            "workflow_definition_sha256, binding_json, created_at) "
            "VALUES (?, 1, 'workflow', 1, ?, '{}', 'now')",
            ("b" * 64, "a" * 64),
        )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "UPDATE harness_workflow_versions SET definition_json = '{}' "
                "WHERE id = 'workflow-0010'"
            )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "DELETE FROM harness_workflow_versions WHERE id = 'workflow-0010'"
            )
        assert conn.execute("PRAGMA foreign_key_check").fetchall() == []
    monkeypatch.setattr(migrations, "MIGRATIONS", all_migrations)
    assert run_migrations(db) == ["0011_harness_definition_snapshots"]


def test_repeat_run_is_idempotent(tmp_path: Path) -> None:
    db = tmp_path / "repeat.sqlite"
    first = run_migrations(db)
    assert first
    with sqlite3.connect(db) as conn:
        before = conn.execute("SELECT name FROM sqlite_master ORDER BY name").fetchall()
    assert run_migrations(db) == []
    with sqlite3.connect(db) as conn:
        after = conn.execute("SELECT name FROM sqlite_master ORDER BY name").fetchall()
        rows = conn.execute("SELECT COUNT(*) FROM pharos_schema_migrations").fetchone()[0]
    assert before == after, "a second boot must not change the schema"
    assert rows == len(migrations.MIGRATIONS)


def test_checksum_mismatch_fails_startup(tmp_path: Path, monkeypatch) -> None:
    db = tmp_path / "tampered.sqlite"
    run_migrations(db)
    # Simulate a build where the committed revision text changed under the
    # same revision id -- the exact thing checksums exist to catch.
    monkeypatch.setattr(
        migrations,
        "MIGRATIONS",
        (
            Migration(
                migrations.MIGRATIONS[0].revision,
                migrations.MIGRATIONS[0].description + " (edited)",
                migrations.MIGRATIONS[0].statements,
            ),
            *migrations.MIGRATIONS[1:],
        ),
    )
    with pytest.raises(MigrationError, match="checksum mismatch"):
        run_migrations(db)


def test_unknown_applied_revision_fails_startup(tmp_path: Path, monkeypatch) -> None:
    db = tmp_path / "unknown.sqlite"
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        conn.execute(
            "INSERT INTO pharos_schema_migrations (revision, description, checksum, applied_at) "
            "VALUES ('9999_from_the_future', 'never heard of it', 'x', datetime('now'))"
        )
        conn.commit()
    with pytest.raises(MigrationError, match="9999_from_the_future"):
        run_migrations(db)


def test_interrupted_migration_rolls_back_everything(tmp_path: Path, monkeypatch) -> None:
    """A failure at any DDL inside the batch leaves no partial state.

    The poison revision creates a table and then raises, so if the batch were
    not atomic the table would survive the rollback. It must not: no table, no
    ledger row, and the database still opens as exactly the pre-batch state.
    """
    db = tmp_path / "interrupted.sqlite"
    run_migrations(db)
    monkeypatch.setattr(migrations, "MIGRATIONS", _poisoned_migrations())
    with pytest.raises(sqlite3.OperationalError, match="nonexistent_column"):
        run_migrations(db)
    monkeypatch.undo()
    with sqlite3.connect(db) as conn:
        tables = {
            row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
        revisions = [
            row[0] for row in conn.execute("SELECT revision FROM pharos_schema_migrations")
        ]
    assert "pharos_fault_probe" not in tables, "the poisoned DDL must roll back"
    assert revisions == [m.revision for m in migrations.MIGRATIONS]


def test_verify_reports_ok_for_intact_ledger(tmp_path: Path) -> None:
    db = tmp_path / "verify.sqlite"
    run_migrations(db)
    rows = verify_migrations(db)
    assert {row["revision"] for row in rows} == {m.revision for m in migrations.MIGRATIONS}


def test_runtime_provenance_is_an_additive_upgrade(tmp_path: Path, monkeypatch) -> None:
    """0008 then 0009 upgrade an existing H1 schema without rebuilding attempts."""
    db = tmp_path / "runtime-upgrade.sqlite"
    all_migrations = migrations.MIGRATIONS
    runtime_index = next(
        index
        for index, migration in enumerate(all_migrations)
        if migration.revision == "0008_harness_attempt_runtime_provenance"
    )
    prior = all_migrations[:runtime_index]
    runtime_migration = all_migrations[runtime_index]
    identity_migration = all_migrations[runtime_index + 1]
    monkeypatch.setattr(migrations, "MIGRATIONS", prior)
    assert run_migrations(db) == [migration.revision for migration in prior]
    monkeypatch.setattr(migrations, "MIGRATIONS", prior + (runtime_migration,))
    assert run_migrations(db) == [runtime_migration.revision]
    monkeypatch.setattr(
        migrations, "MIGRATIONS", prior + (runtime_migration, identity_migration)
    )
    applied = run_migrations(db)
    assert applied == [identity_migration.revision]
    with sqlite3.connect(db) as conn:
        columns = {
            row[1]: row[2].upper()
            for row in conn.execute("PRAGMA table_info(harness_attempts)")
        }
        indexes = {
            row[1]
            for row in conn.execute("PRAGMA index_list(harness_attempts)")
        }
        table_sql = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='harness_attempts'"
        ).fetchone()[0]
    assert {
        "runtime_session_id": "TEXT",
        "child_pid": "INTEGER",
        "deadline_at": "INTEGER",
        "upstream_commit": "TEXT",
        "runtime_hash": "TEXT",
        "profile_hash": "TEXT",
        "policy_hash": "TEXT",
        "protocol_version": "TEXT",
        "delivery_state": "TEXT",
    }.items() <= columns.items()
    assert {
        "ux_harness_attempts_runtime_session_active",
        "ux_harness_attempts_runtime_session",
        "ix_harness_attempts_child_pid",
        "ux_harness_attempts_child_pid_active",
        "ix_harness_attempts_deadline",
        "ix_harness_attempts_delivery",
    } <= indexes
    assert (
        "delivery_state IN ('not_started','sent','acknowledged','unknown','reconciled')"
        in table_sql
    )
    # Running the new migration twice is a no-op and does not recreate indexes.
    assert run_migrations(db) == []


def test_runtime_identity_constraints_cover_terminal_and_active_attempts(tmp_path: Path) -> None:
    """Session ids never repeat; PIDs may repeat only after termination."""
    db = tmp_path / "runtime-identity.sqlite"
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        conn.execute("PRAGMA foreign_keys=ON")
        _insert_attempt(
            conn,
            "active-session",
            state="running",
            runtime_session_id="session-once",
            child_pid=100,
        )
        with pytest.raises(sqlite3.IntegrityError):
            _insert_attempt(
                conn,
                "terminal-session-reuse",
                state="succeeded",
                runtime_session_id="session-once",
                child_pid=101,
            )
        with pytest.raises(sqlite3.IntegrityError):
            _insert_attempt(
                conn,
                "active-session-reuse",
                state="leased",
                runtime_session_id="session-once",
                child_pid=102,
            )

        _insert_attempt(conn, "terminal-pid", state="succeeded", child_pid=200)
        _insert_attempt(conn, "terminal-pid-again", state="failed", child_pid=200)
        _insert_attempt(conn, "active-pid", state="leased", child_pid=200)
        with pytest.raises(sqlite3.IntegrityError):
            _insert_attempt(conn, "active-pid-reuse", state="running", child_pid=200)

        _insert_attempt(conn, "active-null-pid-1", state="running")
        _insert_attempt(conn, "active-null-pid-2", state="leased")


def test_runtime_identity_upgrade_rolls_back_on_existing_active_pid_conflict(
    tmp_path: Path, monkeypatch
) -> None:
    """0009 rolls back its first index when the second index finds a conflict."""
    db = tmp_path / "runtime-conflict.sqlite"
    all_migrations = migrations.MIGRATIONS
    runtime_index = next(
        index
        for index, migration in enumerate(all_migrations)
        if migration.revision == "0008_harness_attempt_runtime_provenance"
    )
    through_0008 = all_migrations[: runtime_index + 1]
    monkeypatch.setattr(migrations, "MIGRATIONS", through_0008)
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        conn.execute("PRAGMA foreign_keys=ON")
        _insert_attempt(
            conn,
            "conflicting-active-1",
            state="running",
            runtime_session_id="session-one",
            child_pid=400,
        )
        _insert_attempt(
            conn,
            "conflicting-active-2",
            state="leased",
            runtime_session_id="session-two",
            child_pid=400,
        )

    monkeypatch.setattr(migrations, "MIGRATIONS", all_migrations)
    with pytest.raises(sqlite3.IntegrityError):
        run_migrations(db)
    with sqlite3.connect(db) as conn:
        indexes = {row[1] for row in conn.execute("PRAGMA index_list(harness_attempts)")}
        revisions = [
            row[0] for row in conn.execute("SELECT revision FROM pharos_schema_migrations")
        ]
    assert "ux_harness_attempts_runtime_session" not in indexes
    assert "ux_harness_attempts_child_pid_active" not in indexes
    assert revisions == [migration.revision for migration in through_0008]


def test_runtime_identity_race_is_fenced_across_file_connections(tmp_path: Path) -> None:
    """Two writers racing on a file-backed DB cannot claim one active PID."""
    db = tmp_path / "runtime-race.sqlite"
    run_migrations(db)

    barrier = threading.Barrier(2)
    outcomes: list[str] = []

    def claim(attempt_id: str, child_pid: int) -> None:
        connection = sqlite3.connect(db, timeout=5, isolation_level=None)
        connection.execute("PRAGMA foreign_keys=ON")
        connection.execute("PRAGMA busy_timeout=5000")
        try:
            barrier.wait(timeout=5)
            connection.execute("BEGIN IMMEDIATE")
            _claim_attempt(
                connection,
                attempt_id,
                runtime_session_id=f"session-{attempt_id}",
                child_pid=child_pid,
            )
            connection.execute("COMMIT")
            outcomes.append("committed")
        except sqlite3.IntegrityError:
            connection.execute("ROLLBACK")
            outcomes.append("rejected")
        finally:
            connection.close()

    threads = [
        threading.Thread(target=claim, args=("race-a-claim", 301)),
        threading.Thread(target=claim, args=("race-b-claim", 301)),
    ]
    # The parent graph for each attempted row must exist before either writer
    # opens its transaction; add it in one committed setup connection.
    with sqlite3.connect(db) as conn:
        for attempt_id in ("race-a-claim", "race-b-claim"):
            _insert_attempt(conn, attempt_id, state="running")
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join(timeout=10)
        assert not thread.is_alive(), "race writer did not finish"
    assert sorted(outcomes) == ["committed", "rejected"]
    with sqlite3.connect(db) as conn:
        claimed = conn.execute(
            "SELECT runtime_session_id, child_pid FROM harness_attempts "
            "WHERE id IN ('race-a-claim', 'race-b-claim') AND child_pid IS NOT NULL"
        ).fetchall()
    assert len(claimed) == 1
    assert claimed[0][0] in {"session-race-a-claim", "session-race-b-claim"}
    assert claimed[0][1] == 301


def test_fixture_generated_from_the_published_schema_upgrades(tmp_path: Path) -> None:
    """The checked-in legacy fixture is a real pre-Harness database.

    It must upgrade through the same runner as a fresh database, and the
    upgrade must not disturb the legacy tables, rows, indexes or FTS it
    carries. Regenerate with ``python tests/harness/fixtures/generate_legacy_fixture.py``
    when the historical schema contract is deliberately revisited.
    """
    fixture = FIXTURES / "legacy-schema-v0.sqlite"
    assert fixture.is_file(), "fixture missing; run the generator and commit the file"
    upgraded = tmp_path / "upgraded.sqlite"
    upgraded.write_bytes(fixture.read_bytes())

    with sqlite3.connect(upgraded) as conn:
        before = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
    applied = run_migrations(upgraded)
    assert applied == [m.revision for m in migrations.MIGRATIONS]

    with sqlite3.connect(upgraded) as conn:
        after_users = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
        indexes = {
            row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='index'")
        }
    assert before == after_users, "the upgrade must not touch legacy rows"
    assert "ix_papers_user_id" in indexes or any(
        "papers" in name and "user_id" in name for name in indexes
    ), "legacy indexes must survive the upgrade"


def test_ledger_table_is_not_confused_with_business_schema(tmp_path: Path) -> None:
    """The ledger is the runner's own, and only the runner writes it."""
    db = tmp_path / "ledger.sqlite"
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        cols = {row[1] for row in conn.execute("PRAGMA table_info(pharos_schema_migrations)")}
    assert cols == {"revision", "description", "checksum", "applied_at"}


def test_definition_binding_upgrade_keeps_old_rows_unbound(
    tmp_path: Path, monkeypatch
) -> None:
    """0010/0011 add no columns to legacy Run/Attempt rows and do not backfill."""
    db = tmp_path / "definition-binding-upgrade.sqlite"
    all_migrations = migrations.MIGRATIONS
    prior = all_migrations[:-2]
    monkeypatch.setattr(migrations, "MIGRATIONS", prior)
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        conn.execute("PRAGMA foreign_keys=ON")
        _insert_attempt(conn, "legacy-attempt", state="succeeded")
        old_run = conn.execute(
            "SELECT state, workflow_key, workflow_version, definition_sha256, "
            "input_json, input_sha256 FROM harness_runs "
            "WHERE id = 'run-legacy-attempt'"
        ).fetchone()
        old_attempt = conn.execute(
            "SELECT state, runtime_hash, profile_hash, policy_hash FROM harness_attempts "
            "WHERE id = 'legacy-attempt'"
        ).fetchone()

    monkeypatch.setattr(migrations, "MIGRATIONS", all_migrations)
    assert run_migrations(db) == [m.revision for m in all_migrations[-2:]]
    with sqlite3.connect(db) as conn:
        assert conn.execute(
            "SELECT state, workflow_key, workflow_version, definition_sha256, "
            "input_json, input_sha256 FROM harness_runs "
            "WHERE id = 'run-legacy-attempt'"
        ).fetchone() == old_run
        assert conn.execute(
            "SELECT state, workflow_key, workflow_version, definition_sha256, "
            "input_json, input_sha256 FROM harness_runs "
            "WHERE id = 'run-legacy-attempt'"
        ).fetchone() == old_run
        assert conn.execute(
            "SELECT state, runtime_hash, profile_hash, policy_hash FROM harness_attempts "
            "WHERE id = 'legacy-attempt'"
        ).fetchone() == old_attempt
        assert conn.execute(
            "SELECT COUNT(*) FROM harness_run_definition_snapshots"
        ).fetchone()[0] == 0
        assert conn.execute(
            "SELECT COUNT(*) FROM harness_attempt_definition_snapshots"
        ).fetchone()[0] == 0


def test_definition_snapshot_migration_is_atomic(
    tmp_path: Path, monkeypatch
) -> None:
    """A late 0011 failure removes its tables and ledger row atomically."""
    db = tmp_path / "definition-binding-rollback.sqlite"
    all_migrations = migrations.MIGRATIONS
    prior = all_migrations[:-1]
    migration = all_migrations[-1]
    monkeypatch.setattr(migrations, "MIGRATIONS", prior)
    run_migrations(db)

    broken = Migration(
        migration.revision,
        migration.description,
        migration.statements + ("SELECT nonexistent_column FROM harness_runs",),
    )
    monkeypatch.setattr(migrations, "MIGRATIONS", prior + (broken,))
    with pytest.raises(sqlite3.OperationalError, match="nonexistent_column"):
        run_migrations(db)
    with sqlite3.connect(db) as conn:
        objects = {
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE name LIKE 'harness_%' "
                "OR name = 'ux_harness_workflow_versions_key_version_hash'"
            )
        }
        run_columns = {row[1] for row in conn.execute("PRAGMA table_info(harness_runs)")}
        attempt_columns = {row[1] for row in conn.execute("PRAGMA table_info(harness_attempts)")}
        revisions = [
            row[0] for row in conn.execute("SELECT revision FROM pharos_schema_migrations")
        ]
    assert {
        "harness_model_profile_versions",
        "harness_capability_versions",
        "harness_role_versions",
        "harness_workflow_definition_bindings",
    } <= objects
    assert "harness_run_definition_snapshots" not in objects
    assert "harness_attempt_definition_snapshots" not in objects
    assert "definition_binding_sha256" not in run_columns
    assert "definition_binding_sha256" not in attempt_columns
    assert revisions == [migration.revision for migration in prior]

    monkeypatch.setattr(migrations, "MIGRATIONS", all_migrations)
    assert run_migrations(db) == [migration.revision]
    assert run_migrations(db) == []


def test_definition_binding_constraints_reject_invalid_values_and_fks(tmp_path: Path) -> None:
    db = tmp_path / "definition-binding-constraints.sqlite"
    run_migrations(db)
    profile_hash = "a" * 64
    workflow_hash = "b" * 64
    binding_hash = "c" * 64
    with sqlite3.connect(db) as conn:
        conn.execute("PRAGMA foreign_keys=ON")
        conn.execute(
            "INSERT INTO harness_model_profile_versions "
            "(id, profile_key, version, definition_json, definition_sha256, created_at) "
            "VALUES ('profile-1', 'reader', 1, '{}', ?, 'now')",
            (profile_hash,),
        )
        conn.execute(
            "INSERT INTO harness_workflow_versions "
            "(id, workflow_key, version, definition_json, definition_sha256, "
            "input_schema, output_schema, created_at) "
            "VALUES ('workflow-1', 'workflow', 1, '{}', ?, '{}', '{}', 'now')",
            (workflow_hash,),
        )
        conn.execute(
            "INSERT INTO harness_workflow_definition_bindings "
            "(binding_sha256, schema_version, workflow_key, workflow_version, "
            "workflow_definition_sha256, binding_json, created_at) "
            "VALUES (?, 1, 'workflow', 1, ?, '{}', 'now')",
            (binding_hash, workflow_hash),
        )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "UPDATE harness_model_profile_versions SET definition_json = '{}' "
                "WHERE id = 'profile-1'"
            )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "DELETE FROM harness_workflow_definition_bindings "
                "WHERE binding_sha256 = ?",
                (binding_hash,),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_role_versions "
                "(id, role_key, version, definition_json, definition_sha256, runtime_kind, "
                "model_profile_key, model_profile_version, model_profile_sha256, created_at) "
                "VALUES ('bad-runtime', 'reader', 1, '{}', ?, 'unknown', 'reader', 1, ?, 'now')",
                ("d" * 64, profile_hash),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_role_versions "
                "(id, role_key, version, definition_json, definition_sha256, runtime_kind, "
                "model_profile_key, model_profile_version, model_profile_sha256, created_at) "
                "VALUES ('bad-fk', 'reader', 1, '{}', ?, 'dsh', 'missing', 1, ?, 'now')",
                ("e" * 64, profile_hash),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_model_profile_versions "
                "(id, profile_key, version, definition_json, definition_sha256, created_at) "
                "VALUES ('bad-version', 'bad-version', 0, '{}', ?, 'now')",
                ("1" * 64,),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_model_profile_versions "
                "(id, profile_key, version, definition_json, definition_sha256, created_at) "
                "VALUES ('bad-hash', 'bad-hash', 1, '{}', ?, 'now')",
                ("A" * 64,),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_role_versions "
                "(id, role_key, version, definition_json, definition_sha256, runtime_kind, "
                "model_profile_key, model_profile_version, model_profile_sha256, created_at) "
                "VALUES ('bad-profile-key', 'bad-profile-key', 1, '{}', ?, 'dsh', ?, 1, ?, 'now')",
                ("3" * 64, "k" * 65, profile_hash),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_workflow_definition_bindings "
                "(binding_sha256, schema_version, workflow_key, workflow_version, "
                "workflow_definition_sha256, binding_json, created_at) "
                "VALUES (?, 2, 'workflow', 1, ?, '{}', 'now')",
                ("4" * 64, workflow_hash),
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_workflow_definition_bindings "
                "(binding_sha256, schema_version, workflow_key, workflow_version, "
                "workflow_definition_sha256, binding_json, created_at) "
                "VALUES (?, 1, 'missing', 1, ?, '{}', 'now')",
                ("5" * 64, workflow_hash),
            )
        _insert_attempt(conn, "binding-attempt", state="running")
        run_id = "run-binding-attempt"
        role_hash = "6" * 64
        policy_hash = "f" * 64
        route_hash = "2" * 64
        conn.execute(
            "UPDATE harness_runs SET definition_sha256 = ? WHERE id = ?",
            (workflow_hash, run_id),
        )
        conn.execute(
            "INSERT INTO harness_role_versions "
            "(id, role_key, version, definition_json, definition_sha256, runtime_kind, "
            "model_profile_key, model_profile_version, model_profile_sha256, created_at) "
            "VALUES ('role-1', 'reader', 1, '{}', ?, 'dsh', 'reader', 1, ?, 'now')",
            (role_hash, profile_hash),
        )
        capability_hash = "9" * 64
        conn.execute(
            "INSERT INTO harness_capability_versions "
            "(id, capability_key, version, definition_json, definition_sha256, created_at) "
            "VALUES ('capability-1', 'retrieval', 1, '{}', ?, 'now')",
            (capability_hash,),
        )
        conn.execute(
            "INSERT INTO harness_run_definition_snapshots "
            "(run_id, scope_type, scope_id, workflow_key, workflow_version, "
            "workflow_definition_sha256, definition_binding_sha256, "
            "policy_snapshot_schema_version, policy_snapshot_sha256, policy_snapshot_json, "
            "created_at) VALUES (?, 'user', 'constraint-test', 'workflow', 1, ?, ?, 1, ?, "
            "'{}', 'now')",
            (run_id, workflow_hash, binding_hash, policy_hash),
        )
        conn.execute(
            "INSERT INTO harness_attempt_definition_snapshots "
            "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
            "definition_binding_sha256, run_policy_sha256, executor_kind, executor_identity, "
            "executor_role_key, executor_role_version, executor_role_definition_sha256, "
            "model_profile_identity, model_profile_key, "
            "model_profile_version, "
            "model_profile_sha256, model_route_key, model_route_sha256, provider, model, "
            "usage_source, created_at) "
            "VALUES ('binding-attempt', ?, 'user', 'constraint-test', 'step-binding-attempt', 1, "
            "?, ?, 'role', 'reader@1', 'reader', 1, ?, "
            "'reader@1', 'reader', 1, ?, 'route', ?, 'provider', 'model', 'official', 'now')",
            (run_id, binding_hash, policy_hash, role_hash, profile_hash, route_hash),
        )

        def insert_role_attempt(attempt_id: str, attempt_no: int) -> None:
            conn.execute(
                "INSERT INTO harness_attempts "
                "(id, step_id, run_id, scope_type, scope_id, attempt_no, state) "
                "VALUES (?, 'step-binding-attempt', ?, 'user', 'constraint-test', ?, 'running')",
                (attempt_id, run_id, attempt_no),
            )

        _insert_attempt(conn, "capability-attempt", state="running")
        capability_run_id = "run-capability-attempt"
        conn.execute(
            "UPDATE harness_runs SET definition_sha256 = ? WHERE id = ?",
            (workflow_hash, capability_run_id),
        )
        conn.execute(
            "INSERT INTO harness_run_definition_snapshots "
            "(run_id, scope_type, scope_id, workflow_key, workflow_version, "
            "workflow_definition_sha256, definition_binding_sha256, "
            "policy_snapshot_schema_version, policy_snapshot_sha256, policy_snapshot_json, "
            "created_at) VALUES (?, 'user', 'constraint-test', 'workflow', 1, ?, ?, 1, ?, "
            "'{}', 'now')",
            (capability_run_id, workflow_hash, binding_hash, "a" * 64),
        )
        conn.execute(
            "INSERT INTO harness_attempt_definition_snapshots "
            "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
            "definition_binding_sha256, run_policy_sha256, executor_kind, executor_identity, "
            "executor_capability_key, executor_capability_version, "
            "executor_capability_definition_sha256, created_at) "
            "VALUES ('capability-attempt', ?, 'user', 'constraint-test', "
            "'step-capability-attempt', 1, ?, ?, 'capability', 'retrieval@1', "
            "'retrieval', 1, ?, 'now')",
            (capability_run_id, binding_hash, "a" * 64, capability_hash),
        )

        insert_role_attempt("wrong-profile", 2)
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, executor_identity, "
                "executor_role_key, executor_role_version, executor_role_definition_sha256, "
                "model_profile_identity, model_profile_key, "
                "model_profile_version, "
                "model_profile_sha256, model_route_key, model_route_sha256, provider, model, "
                "usage_source, created_at) "
                "VALUES ('wrong-profile', ?, 'user', 'constraint-test', "
                "'step-binding-attempt', 2, "
                "?, ?, 'role', 'reader@1', 'reader', 1, ?, "
                "'wrong@1', 'wrong', 1, ?, 'route', ?, 'provider', 'model', 'official', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, profile_hash, route_hash),
            )

        insert_role_attempt("wrong-profile-identity", 3)
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, executor_identity, "
                "executor_role_key, executor_role_version, executor_role_definition_sha256, "
                "model_profile_identity, model_profile_key, "
                "model_profile_version, "
                "model_profile_sha256, model_route_key, model_route_sha256, provider, model, "
                "usage_source, created_at) "
                "VALUES ('wrong-profile-identity', ?, 'user', 'constraint-test', "
                "'step-binding-attempt', 3, "
                "?, ?, 'role', 'reader@1', 'reader', 1, ?, "
                "'not-reader@1', 'reader', 1, ?, 'route', ?, 'provider', 'model', "
                "'official', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, profile_hash, route_hash),
            )

        insert_role_attempt("bad-route-hash", 4)
        with pytest.raises(sqlite3.IntegrityError, match="CHECK constraint failed"):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, "
                "executor_identity, executor_role_key, executor_role_version, "
                "executor_role_definition_sha256, model_profile_identity, "
                "model_profile_key, model_profile_version, model_profile_sha256, "
                "model_route_key, model_route_sha256, provider, model, usage_source, "
                "created_at) VALUES ('bad-route-hash', ?, 'user', 'constraint-test', "
                "'step-binding-attempt', 4, ?, ?, 'role', 'reader@1', 'reader', 1, ?, "
                "'reader@1', 'reader', 1, ?, 'route', ?, 'provider', 'model', "
                "'official', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, profile_hash, "A" * 64),
            )

        insert_role_attempt("bad-usage-source", 5)
        with pytest.raises(sqlite3.IntegrityError, match="CHECK constraint failed"):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, "
                "executor_identity, executor_role_key, executor_role_version, "
                "executor_role_definition_sha256, model_profile_identity, "
                "model_profile_key, model_profile_version, model_profile_sha256, "
                "model_route_key, model_route_sha256, provider, model, usage_source, "
                "created_at) VALUES ('bad-usage-source', ?, 'user', 'constraint-test', "
                "'step-binding-attempt', 5, ?, ?, 'role', 'reader@1', 'reader', 1, ?, "
                "'reader@1', 'reader', 1, ?, 'route', ?, 'provider', 'model', "
                "'unknown', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, profile_hash, route_hash),
            )

        insert_role_attempt("bad-profile-hash", 6)
        with pytest.raises(sqlite3.IntegrityError, match="CHECK constraint failed"):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, "
                "executor_identity, executor_role_key, executor_role_version, "
                "executor_role_definition_sha256, model_profile_identity, "
                "model_profile_key, model_profile_version, model_profile_sha256, "
                "model_route_key, model_route_sha256, provider, model, usage_source, "
                "created_at) VALUES ('bad-profile-hash', ?, 'user', 'constraint-test', "
                "'step-binding-attempt', 6, ?, ?, 'role', 'reader@1', 'reader', 1, ?, "
                "'reader@1', 'reader', 1, ?, 'route', ?, 'provider', 'model', "
                "'official', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, "A" * 64, route_hash),
            )

        insert_role_attempt("wrong-executor-identity", 7)
        with pytest.raises(sqlite3.IntegrityError, match="CHECK constraint failed"):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, "
                "executor_identity, executor_role_key, executor_role_version, "
                "executor_role_definition_sha256, model_profile_identity, "
                "model_profile_key, model_profile_version, model_profile_sha256, "
                "model_route_key, model_route_sha256, provider, model, usage_source, "
                "created_at) VALUES ('wrong-executor-identity', ?, 'user', "
                "'constraint-test', 'step-binding-attempt', 7, ?, ?, 'role', "
                "'writer@1', 'reader', 1, ?, 'reader@1', 'reader', 1, ?, 'route', ?, "
                "'provider', 'model', 'official', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, profile_hash, route_hash),
            )

        insert_role_attempt("missing-role-route", 8)
        with pytest.raises(sqlite3.IntegrityError, match="CHECK constraint failed"):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, "
                "executor_identity, executor_role_key, executor_role_version, "
                "executor_role_definition_sha256, model_profile_identity, "
                "model_profile_key, model_profile_version, model_profile_sha256, "
                "provider, model, usage_source, created_at) VALUES "
                "('missing-role-route', ?, 'user', 'constraint-test', "
                "'step-binding-attempt', 8, ?, ?, 'role', 'reader@1', 'reader', 1, ?, "
                "'reader@1', 'reader', 1, ?, 'provider', 'model', 'official', 'now')",
                (run_id, binding_hash, policy_hash, role_hash, profile_hash),
            )

        conn.execute(
            "INSERT INTO harness_attempts "
            "(id, step_id, run_id, scope_type, scope_id, attempt_no, state) "
            "VALUES ('capability-with-model', 'step-capability-attempt', ?, 'user', "
            "'constraint-test', 2, 'running')",
            (capability_run_id,),
        )
        with pytest.raises(sqlite3.IntegrityError, match="CHECK constraint failed"):
            conn.execute(
                "INSERT INTO harness_attempt_definition_snapshots "
                "(attempt_id, run_id, scope_type, scope_id, step_id, attempt_no, "
                "definition_binding_sha256, run_policy_sha256, executor_kind, "
                "executor_identity, executor_capability_key, executor_capability_version, "
                "executor_capability_definition_sha256, model_profile_identity, "
                "model_profile_key, model_profile_version, model_profile_sha256, "
                "model_route_key, model_route_sha256, provider, model, usage_source, "
                "created_at) VALUES ('capability-with-model', ?, 'user', 'constraint-test', "
                "'step-capability-attempt', 2, ?, ?, 'capability', 'retrieval@1', "
                "'retrieval', 1, ?, 'reader@1', 'reader', 1, ?, 'route', ?, "
                "'provider', 'model', 'official', 'now')",
                (
                    capability_run_id,
                    binding_hash,
                    "a" * 64,
                    capability_hash,
                    profile_hash,
                    route_hash,
                ),
            )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "UPDATE harness_attempt_definition_snapshots SET run_policy_sha256 = ? "
                "WHERE attempt_id = 'binding-attempt'",
                ("8" * 64,),
            )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "DELETE FROM harness_attempt_definition_snapshots "
                "WHERE attempt_id = 'binding-attempt'"
            )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "UPDATE harness_run_definition_snapshots SET policy_snapshot_json = '{}' "
                "WHERE run_id = ?",
                (run_id,),
            )
        with pytest.raises(sqlite3.IntegrityError, match="immutable"):
            conn.execute(
                "DELETE FROM harness_run_definition_snapshots WHERE run_id = ?",
                (run_id,),
            )
        with pytest.raises(sqlite3.IntegrityError, match="frozen"):
            conn.execute(
                "UPDATE harness_runs SET workflow_key = 'rewritten' "
                "WHERE id = ?",
                (run_id,),
            )
        with pytest.raises(sqlite3.IntegrityError, match="frozen"):
            conn.execute(
                "UPDATE harness_runs SET policy_snapshot_json = '{\"mutated\":true}' "
                "WHERE id = ?",
                (run_id,),
            )
        with pytest.raises(sqlite3.IntegrityError, match="cannot be deleted"):
            conn.execute("DELETE FROM harness_runs WHERE id = ?", (run_id,))
        with pytest.raises(sqlite3.IntegrityError, match="cannot be deleted"):
            conn.execute("DELETE FROM harness_attempts WHERE id = 'binding-attempt'")
        with pytest.raises(sqlite3.IntegrityError, match="frozen"):
            conn.execute(
                "UPDATE harness_attempts SET attempt_no = 99 "
                "WHERE id = 'binding-attempt'"
            )
