"""The versioned migration runner: the H0 foundation tests.

Covers the six code gates the implementation plan names for migrations:

- fresh DB: an empty directory boots and the ledger records every revision;
- repeat: consecutive boots apply nothing new and change nothing;
- checksum mismatch: editing a committed migration fails startup;
- unknown/missing revision: a ledger this build does not know fails startup;
- interrupted migration: a failure inside the batch rolls everything back --
  no new revision, no partial DDL -- at every injected failure point;
- fixture upgrade: a checked-in legacy-schema fixture (generated by
  ``fixtures/generate_legacy_fixture.py`` from the last published schema
  contract) upgrades with every legacy table, row and index intact.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest
from pharos.db import migrations
from pharos.db.migrations import Migration, MigrationError, run_migrations, verify_migrations

FIXTURES = Path(__file__).parent / "fixtures"


def _poisoned_migrations() -> tuple[Migration, ...]:
    """The real migrations plus a deliberately failing revision.

    The poison creates a table and then raises inside the same transaction,
    which is the exact shape of "DDL succeeded, ledger insert never ran" that
    the rollback gate must catch.
    """
    return migrations.MIGRATIONS + (
        Migration(
            revision="9999_poison",
            description="Deliberate failure for fault injection",
            statements=(
                "CREATE TABLE pharos_fault_probe (id INTEGER PRIMARY KEY)",
                # RAISE() only exists inside triggers; a missing column is the
                # equivalent deterministic statement error here.
                "SELECT nonexistent_column FROM pharos_fault_probe",
            ),
        ),
    )


def test_fresh_database_applies_every_revision(tmp_path: Path) -> None:
    db = tmp_path / "fresh.sqlite"
    applied = run_migrations(db)
    assert applied == [m.revision for m in migrations.MIGRATIONS]
    with sqlite3.connect(db) as conn:
        row = conn.execute(
            "SELECT revision, description FROM pharos_schema_migrations ORDER BY revision"
        ).fetchone()
    assert row is not None and row[0] == migrations.MIGRATIONS[0].revision


def test_repeat_run_is_idempotent(tmp_path: Path) -> None:
    db = tmp_path / "repeat.sqlite"
    first = run_migrations(db)
    assert first
    with sqlite3.connect(db) as conn:
        before = conn.execute("SELECT name FROM sqlite_master ORDER BY name").fetchall()
    assert run_migrations(db) == []
    with sqlite3.connect(db) as conn:
        after = conn.execute("SELECT name FROM sqlite_master ORDER BY name").fetchall()
        rows = conn.execute("SELECT COUNT(*) FROM pharos_schema_migrations").fetchone()[0]
    assert before == after, "a second boot must not change the schema"
    assert rows == len(migrations.MIGRATIONS)


def test_checksum_mismatch_fails_startup(tmp_path: Path, monkeypatch) -> None:
    db = tmp_path / "tampered.sqlite"
    run_migrations(db)
    # Simulate a build where the committed revision text changed under the
    # same revision id -- the exact thing checksums exist to catch.
    monkeypatch.setattr(
        migrations,
        "MIGRATIONS",
        (
            Migration(
                migrations.MIGRATIONS[0].revision,
                migrations.MIGRATIONS[0].description + " (edited)",
                migrations.MIGRATIONS[0].statements,
            ),
            *migrations.MIGRATIONS[1:],
        ),
    )
    with pytest.raises(MigrationError, match="checksum mismatch"):
        run_migrations(db)


def test_unknown_applied_revision_fails_startup(tmp_path: Path, monkeypatch) -> None:
    db = tmp_path / "unknown.sqlite"
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        conn.execute(
            "INSERT INTO pharos_schema_migrations (revision, description, checksum, applied_at) "
            "VALUES ('9999_from_the_future', 'never heard of it', 'x', datetime('now'))"
        )
        conn.commit()
    with pytest.raises(MigrationError, match="9999_from_the_future"):
        run_migrations(db)


def test_interrupted_migration_rolls_back_everything(tmp_path: Path, monkeypatch) -> None:
    """A failure at any DDL inside the batch leaves no partial state.

    The poison revision creates a table and then raises, so if the batch were
    not atomic the table would survive the rollback. It must not: no table, no
    ledger row, and the database still opens as exactly the pre-batch state.
    """
    db = tmp_path / "interrupted.sqlite"
    run_migrations(db)
    monkeypatch.setattr(migrations, "MIGRATIONS", _poisoned_migrations())
    with pytest.raises(sqlite3.OperationalError, match="nonexistent_column"):
        run_migrations(db)
    monkeypatch.undo()
    with sqlite3.connect(db) as conn:
        tables = {
            row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
        revisions = [
            row[0] for row in conn.execute("SELECT revision FROM pharos_schema_migrations")
        ]
    assert "pharos_fault_probe" not in tables, "the poisoned DDL must roll back"
    assert revisions == [m.revision for m in migrations.MIGRATIONS]


def test_verify_reports_ok_for_intact_ledger(tmp_path: Path) -> None:
    db = tmp_path / "verify.sqlite"
    run_migrations(db)
    rows = verify_migrations(db)
    assert {row["revision"] for row in rows} == {m.revision for m in migrations.MIGRATIONS}


def test_fixture_generated_from_the_published_schema_upgrades(tmp_path: Path) -> None:
    """The checked-in legacy fixture is a real pre-Harness database.

    It must upgrade through the same runner as a fresh database, and the
    upgrade must not disturb the legacy tables, rows, indexes or FTS it
    carries. Regenerate with ``python tests/harness/fixtures/generate_legacy_fixture.py``
    when the historical schema contract is deliberately revisited.
    """
    fixture = FIXTURES / "legacy-schema-v0.sqlite"
    assert fixture.is_file(), "fixture missing; run the generator and commit the file"
    upgraded = tmp_path / "upgraded.sqlite"
    upgraded.write_bytes(fixture.read_bytes())

    with sqlite3.connect(upgraded) as conn:
        before = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
    applied = run_migrations(upgraded)
    assert applied == [m.revision for m in migrations.MIGRATIONS]

    with sqlite3.connect(upgraded) as conn:
        after_users = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
        indexes = {
            row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='index'")
        }
    assert before == after_users, "the upgrade must not touch legacy rows"
    assert "ix_papers_user_id" in indexes or any(
        "papers" in name and "user_id" in name for name in indexes
    ), "legacy indexes must survive the upgrade"


def test_ledger_table_is_not_confused_with_business_schema(tmp_path: Path) -> None:
    """The ledger is the runner's own, and only the runner writes it."""
    db = tmp_path / "ledger.sqlite"
    run_migrations(db)
    with sqlite3.connect(db) as conn:
        cols = {row[1] for row in conn.execute("PRAGMA table_info(pharos_schema_migrations)")}
    assert cols == {"revision", "description", "checksum", "applied_at"}
